export default {
  version: '0.2',
  language: 'en',
  words: [
    'saavn',
    'Saya',
    'apikey',
    'sumit',
    'kolhe',
    'shnwaz',
    'shnwazdev',
    'shnwazdeveloper',
    'jiosaavn',
    'maxage',
    'asynciterable',
    'albumid',
    'blurryface',
    'jiotune',
    'Kesariya',
    'KHTML',
    'listid',
    'sumitkolhe',
    'kbps',
    'Moxt',
    'numsongs',
    'Ogwhbht',
    'perma',
    'firstname',
    'lastname',
    'pids',
    'stationid',
    'topbar',
    'topquery',
    'vcode',
    'webapi',
    'webradio'
  ],
  ignorePaths: ['**/node_modules/**', 'dist', 'coverage', '.vscode', '.vercel-sim', 'CHANGELOG.md']
}
